### ISSUE TITLE
please give a sample command about inference

### ISSUE THREAD

**Issue by franztao** [Marhabibi/DeepTable#2]
description:
i use the command "DeepTableEval.py -m outut/model-98-0.9708-0.7618-0.9013-0.7748.hdf5  -i  /projects/1002_origin/1031701018101328.jpg    -o output" ,return unkown error ,such as below:

Using TensorFlow backend.
/projects/1002_origin/1031701018101328.jpg
test
Traceback (most recent call last):
  File "DeepTableEval.py", line 32, in <module>
    X_test,y_test,dictionary = transform_tables(inp, "test")
  File "/projects/DeepTable/input_transformation.py", line 22, in transform_tables
    [X,y] = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\xff'.

**Comment by franztao** [comment]
input this command  "DeepTableEval.py -m outut/model-98-0.9708-0.7618-0.9013-0.7748.hdf5  -i  /projects/DeepTable/tables.pickle    -o output " return as beblow:

Using TensorFlow backend.
/projects/DeepTable/tables.pickle
test
Traceback (most recent call last):
  File "DeepTableEval.py", line 35, in <module>
    model = load_model(md1)
  File "/root/miniconda3/envs/DeepTable-py3.7/lib/python3.7/site-packages/keras/models.py", line 238, in load_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
